org: serverlessstudy
service: webscraper-node-challenge

stages: 
  default:
    params:
      TABLE_NAME: "ProductsTable"
      BUCKET_NAME: "nws-products-api-bucket"

plugins:
  - "@serverless-aws/serverless-s3-remover"

custom:
  remover:
    buckets:
      - nws-products-api-bucket


provider:
  name: aws
  runtime: nodejs20.x
  stage: "dev"
  region: "us-east-1"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - s3:*
          Resource:
            - Fn::GetAtt: [ProductsTable, Arn]
  environment:
    PRODUCTS_TABLE: ${self:stages.default.params.TABLE_NAME}
    BUCKET_NAME: ${self:stages.default.params.BUCKET_NAME}

functions:

  GetProducts:
    handler: src/handlers/GetProducts.handler
    description: Get all products from db
    events:
      - http: 
          path: /products
          method: get

  GetProductById:
    handler: src/handlers/GetProductById.handler
    description: Get product from db by id.
    events:
      - http: 
          path: /products/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
                
  UploadProductImage:
    handler: src/handlers/UploadProductImage.handler
    description: Update product Image on s3 bucket and updates the product image
    events:
      - http:
          path: /products/{id}/upload
          method: patch
          request:
            parameters:
              paths:
                id: true
      
  DeleteProduct:
    handler: src/handlers/DeleteProduct.handler
    description: Delete product in db by id 
    events:
      - http:
          path: products/{id}
          method: delete    
          request:
            parameters:
              paths:
                id: true
    
resources:
  Resources:
    ProductsImageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: nws-products-api-bucket
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false 
          BlockPublicPolicy: false 
          IgnorePublicAcls: false
          RestrictPublicBuckets: false

    ProductsImageBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: nws-products-api-bucket
        PolicyDocument:
          Statement: 
            - Effect: Allow 
              Principal: "*"
              Action: s3:GetObject
              Resource: arn:aws:s3:::nws-products-api-bucket/*
            - Effect: Allow
              Principal: "*"
              Action: s3:PutObject
              Resource: arn:aws:s3:::nws-products-api-bucket/*
            - Effect: Allow
              Principal: "*"
              Action: s3:DeleteObject
              Resource: arn:aws:s3:::nws-products-api-bucket/*

    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK 
            AttributeType: S 
          - AttributeName: name 
            AttributeType: S 
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: NameIndex
            KeySchema: 
              - AttributeName: name
                KeyType: HASH
            Projection: 
              ProjectionType: ALL                          
        TableName: ProductsTable
